### ISSUE TITLE
how to host?

### ISSUE THREAD

**Issue by ngmisl** [LiamFenneman/leptos-csr#1]
Hi,

tried to host the build's /dist folder here on github pages, but it doesn't really work. How should I do it?

thanks!

**Comment by LiamFenneman** [comment]
Hi,

I assume that you are trying to host a project where the URL that GitHub uses looks like: `example.github.io/my-project/`.
The Leptos router will be trying to serve from `example.github.io` and the assets like JS and WASM have a similar problem.

To solve this you need to add `<base data-trunk-public-url/>` to the `index.html` file at the top of the `<head>` section.

In the `app.rs` file you also need to make a change to use a base URL:
```
        <Router base="example">
            <Routes base={String::from("example")}>
```

Then when building use: `trunk build --release --public-url '/example/'`
Or create a `Trunk.toml` and add:
```
[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/example/"
filehash = true
```

You can replace "example" with the "my-project" part from the GitHub URL.
